"use client";

import { useState } from "react";
import { CrmRecord } from "@/types/crm";

interface GenerateProps {
  onLeadsGenerated: (newLeads: CrmRecord[]) => void;
}

export function GenerateLeadsView({ onLeadsGenerated }: GenerateProps) {
  const [channel, setChannel] = useState("facebook");
  const [isGenerating, setIsGenerating] = useState(false);
  const [successMsg, setSuccessMsg] = useState("");

  const handleGenerate = () => {
    setIsGenerating(true);
    setSuccessMsg("");

    setTimeout(() => {
      // Simulate generated leads based on channel
      const date = new Date().toISOString().replace("T", " ").substring(0, 19);
      const generated: CrmRecord[] = [
        {
          name: `AI Lead: ${channel === "facebook" ? "Rohan" : "Sophia"}`,
          email: `${channel === "facebook" ? "rohan" : "sophia"}@example.com`,
          mobile_without_country_code: channel === "facebook" ? "9876543220" : "555123908",
          country_code: channel === "facebook" ? "+91" : "+1",
          created_at: date,
          company: channel === "facebook" ? "Rohan Consulting" : "Sophia Design Inc",
          city: channel === "facebook" ? "Pune" : "Boston",
          state: channel === "facebook" ? "Maharashtra" : "Massachusetts",
          country: channel === "facebook" ? "India" : "USA",
          lead_owner: "Vikram",
          crm_status: "GOOD_LEAD_FOLLOW_UP",
          crm_note: "Interested in real estate portfolio",
          data_source: "leads_on_demand",
          possession_time: "",
          description: "Auto-generated by AI campaign generator.",
        },
      ];

      onLeadsGenerated(generated);
      setIsGenerating(false);
      setSuccessMsg(`Success! Generated 1 new AI lead from ${channel.toUpperCase()} campaigns.`);
    }, 2000);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold tracking-tight">Generate Leads</h1>
        <p className="mt-1 text-sm text-muted">
          Launch AI lead gen campaigns directly synced to your pipeline funnel.
        </p>
      </div>

      <div className="rounded-lg border border-rule bg-surface p-6 dark:border-dark-rule dark:bg-dark-surface max-w-xl">
        <h3 className="font-bold text-sm mb-4">Select Target Campaign Source</h3>

        <div className="grid grid-cols-3 gap-3 mb-6">
          <button
            onClick={() => setChannel("facebook")}
            className={`flex flex-col items-center justify-center p-4 border rounded-lg hover:border-rust transition ${
              channel === "facebook" ? "border-rust bg-rust-light/20" : "border-rule"
            }`}
          >
            <span className="text-xl">👤</span>
            <span className="text-xs font-bold mt-2">Facebook Ads</span>
          </button>
          <button
            onClick={() => setChannel("google")}
            className={`flex flex-col items-center justify-center p-4 border rounded-lg hover:border-rust transition ${
              channel === "google" ? "border-rust bg-rust-light/20" : "border-rule"
            }`}
          >
            <span className="text-xl">🔍</span>
            <span className="text-xs font-bold mt-2">Google Search</span>
          </button>
          <button
            onClick={() => setChannel("linkedin")}
            className={`flex flex-col items-center justify-center p-4 border rounded-lg hover:border-rust transition ${
              channel === "linkedin" ? "border-rust bg-rust-light/20" : "border-rule"
            }`}
          >
            <span className="text-xl">💼</span>
            <span className="text-xs font-bold mt-2">LinkedIn Leads</span>
          </button>
        </div>

        {successMsg && (
          <div className="mb-4 rounded-md bg-stamp-greenBg px-3 py-2 text-xs text-stamp-green border border-stamp-green/20">
            {successMsg}
          </div>
        )}

        <button
          onClick={handleGenerate}
          disabled={isGenerating}
          className="w-full rounded-md bg-rust px-4 py-2 text-sm font-bold text-white hover:bg-rust-dark transition disabled:opacity-50"
        >
          {isGenerating ? "Simulating AI campaign funnel..." : "Generate AI Lead Now"}
        </button>
      </div>
    </div>
  );
}
